import {inject} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {DOCUMENT, Location} from '@angular/common';
import {UserService} from '../../services/user.service';
import {TokenService} from '../../services/token.service';
import {TrandauService} from '../../services/trandau.service';
import {BocauhoiService} from '../../services/bocauhoi.service';
import {HttpUtilService} from '../../services/http.util.service';
import {ChudeService} from '../../services/chude.service';
import {CauHoiService} from '../../services/cauhoi.service';
import {WsTrandauService} from '../../services/ws-trandau.service';
import {LuyenTapService} from '../../services/luyentap.service';
import {LeaderboardService} from '../../services/leaderboard.service';
import {AdminService} from '../../services/admin.service';
import {AdminStatsService} from '../../services/admin-stats.service';
import {FriendService} from '../../services/friend.service';
import {NotificationService} from '../../services/notification.service';
import {NotificationWsService} from '../../services/notification-ws.service';
import {ToastNotificationService} from '../../services/toast-notification.service';
import {ChatService} from '../../services/chat.service';
import {ChatWsService} from '../../services/chat-ws.service';

export class Base {
  router: Router = inject(Router);
  route: ActivatedRoute = inject(ActivatedRoute);
  userService: UserService = inject(UserService);
  tokenService: TokenService = inject(TokenService);
  tranDauService: TrandauService = inject(TrandauService);
  bocauHoiService: BocauhoiService = inject(BocauhoiService);
  httpUtilService: HttpUtilService = inject(HttpUtilService);
  chuDeService: ChudeService = inject(ChudeService);
  cauHoiService: CauHoiService = inject(CauHoiService);
  wsTrandauService: WsTrandauService = inject(WsTrandauService);
  luyenTapService: LuyenTapService = inject(LuyenTapService);
  leaderboardService: LeaderboardService = inject(LeaderboardService);
  adminService: AdminService = inject(AdminService);
  adminStatsService: AdminStatsService = inject(AdminStatsService);
  friendService: FriendService = inject(FriendService);
  notificationService: NotificationService = inject(NotificationService);
  notificationWsService: NotificationWsService = inject(NotificationWsService);
  toastService: ToastNotificationService = inject(ToastNotificationService);
  protected chatService: ChatService = inject(ChatService);
  protected chatWsService: ChatWsService = inject(ChatWsService);
  document: Document = inject(DOCUMENT);
  location: Location = inject(Location);
}
